### ISSUE TITLE
Fatal error: exception Invalid_argument "KolmogorovSmirnov.two_sample: ties are not allowed"

### ISSUE THREAD

**Issue by UnixJunkie** [superbobry/pareto#41]
Can't you provide a more robust KS-test implementation?

**Comment by UnixJunkie** [comment]
apparently, the one in owl doesn't have this problem: Owl.Stats.ks2_test

**Comment by superbobry** [comment]
Thanks for reporting this. I haven't used KS test for a while, but I vaguely recall that it cannot be applied to samples with ties, therefore the error. I.e. this isn't a robustness issue, but rather a precondition for applying the test.

**Comment by UnixJunkie** [comment]
KS is supposed to be a non parametric test.
If the samples have to satisfy some precondition, I don't call this non parametric.
 You can close if you don't indent to fix; I'll use owl for the time being.

**Comment by superbobry** [comment]
KS is indeed nonparameteric, but IIRC it is intended to be used with continuous random variables which is why ties are not allowed.
